import pandas as pd
from src.database.connection import get_connection
from src.utils.logger import logger


def load_dim_reaction(conn):
    """
    Loads reaction dimension data from the Gold layer CSV into the warehouse.
    The CSV is generated by a separate transformation script.
    """
    logger.info("Starting load for: warehouse.dim_reaction")
    table_name = "warehouse.dim_reaction"
    dim = pd.read_csv("data/gold/dim_reaction.csv")

    with conn.cursor() as cursor:
        cursor.execute(f"TRUNCATE TABLE {table_name} CASCADE;")
        logger.info(f"Cleared {table_name}")

        for _, row in dim.iterrows():
            cursor.execute("""
                INSERT INTO warehouse.dim_reaction
                (reaction_key, reaction_name)
                VALUES (%s,%s)
                """,
                (
                    int(row["reaction_key"]),
                    row["reaction_name"]
                )
            )
    logger.info(f"Successfully loaded {len(dim)} records into {table_name}.")


if __name__ == '__main__':
    # This script now depends on build_dim_reaction.py having been run first.
    # The main entry point should be load_all.py
    connection = get_connection()
    try:
        # For standalone execution, you might want to reset the table first.
        # For this refactor, we assume it's part of the larger `load_all` flow.
        load_dim_reaction(connection)
        connection.commit()
    finally:
        connection.close()